apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplest-k8s
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/jwsy/simplest-k8s
    targetRevision: HEAD
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true
    automated: 
      selfHeal: true
      prune: true


project: default
source:
  repoURL: 'https://github.com/gvermoen/argo-demo'
  path: jade-shooter
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: jade-shooter
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
