apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jade-shooter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gvermoen/argo-demo'
    path: jade-shooter
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jade-shooter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
