apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testkube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubeshop.github.io/helm-charts'
    targetRevision: 1.16.63
    chart: testkube
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: testkube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true





